services:
  silentium:
    image: quay.io/radityprtama/silentium:latest
    container_name: silentium
    ports:
      - "8191:8191"
    environment:
      - HEADLESS=true
    restart: unless-stopped

  api:
    image: quay.io/radityprtama/layarplus-api:latest
    container_name: idlix-api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - SILENTIUM_API_URL=http://silentium:8191
    depends_on:
      - silentium
    restart: unless-stopped
